import React from 'react';

const DisplayDefault = () => {
  return (
    <svg
      width="64px"
      height="64px"
      viewBox="0 0 64 64"
      version="1.1"
      xmlns="http://www.w3.org/2000/svg"
      xmlnsXlink="http://www.w3.org/1999/xlink"
    >
      <title>Group 3</title>
      <g id="page" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
        <g
          id="6.3.1.7.a(D)_首頁_商品分類_分類彈窗"
          transform="translate(-1186.000000, -424.000000)"
        >
          <g id="Group-3" transform="translate(1186.000000, 424.000000)">
            <rect
              id="Rectangle-4-Copy-8"
              stroke="#D6DFF2"
              fill="#FFFFFF"
              x="0.5"
              y="0.5"
              width="63"
              height="63"
              rx="5"
            />
            <rect
              id="Rectangle-Copy-13"
              stroke="#DEDEE0"
              x="9.5"
              y="15.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-17"
              stroke="#DEDEE0"
              x="9.5"
              y="27.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-21"
              stroke="#DEDEE0"
              fill="#EDEDEE"
              x="9.5"
              y="39.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-15"
              stroke="#DEDEE0"
              x="33.5"
              y="15.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-18"
              stroke="#DEDEE0"
              fill="#5B7CE3"
              x="33.5"
              y="27.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-22"
              stroke="#DEDEE0"
              x="33.5"
              y="39.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-14"
              stroke="#DEDEE0"
              fill="#EDEDEE"
              x="21.5"
              y="15.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-19"
              stroke="#DEDEE0"
              x="21.5"
              y="27.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-23"
              stroke="#DEDEE0"
              x="21.5"
              y="39.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-16"
              stroke="#DEDEE0"
              x="45.5"
              y="15.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-20"
              stroke="#DEDEE0"
              x="45.5"
              y="27.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-24"
              stroke="#DEDEE0"
              x="45.5"
              y="39.5"
              width="9"
              height="9"
              rx="2"
            />
          </g>
        </g>
      </g>
    </svg>
  );
};

export default DisplayDefault;
