import React from 'react';

const DisplayPartial = () => {
  return (
    <svg
      width="64px"
      height="64px"
      viewBox="0 0 64 64"
      version="1.1"
      xmlns="http://www.w3.org/2000/svg"
      xmlnsXlink="http://www.w3.org/1999/xlink"
    >
      <title>Group 4</title>
      <g id="page" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
        <g
          id="6.3.1.7.a(D)_首頁_商品分類_分類彈窗"
          transform="translate(-1186.000000, -500.000000)"
        >
          <g id="Group-4" transform="translate(1186.000000, 500.000000)">
            <rect
              id="Rectangle-4-Copy-9"
              stroke="#D6DFF2"
              fill="#FFFFFF"
              x="0.5"
              y="0.5"
              width="63"
              height="63"
              rx="5"
            />
            <rect
              id="Rectangle-Copy-25"
              stroke="#DEDEE0"
              x="9.5"
              y="13.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-37"
              stroke="#DEDEE0"
              x="9.5"
              y="34.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-26"
              fill="#DEDEE0"
              x="9"
              y="25"
              width="10"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-38"
              fill="#DEDEE0"
              x="9"
              y="46"
              width="10"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-32"
              fill="#DEDEE0"
              x="33"
              y="25"
              width="10"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-39"
              fill="#5B7CE3"
              x="33"
              y="46"
              width="10"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-29"
              fill="#DEDEE0"
              x="21"
              y="25"
              width="10"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-40"
              fill="#DEDEE0"
              x="21"
              y="46"
              width="10"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-33"
              fill="#DEDEE0"
              x="45"
              y="25"
              width="10"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-41"
              fill="#DEDEE0"
              x="45"
              y="46"
              width="10"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-27"
              fill="#DEDEE0"
              x="11"
              y="28"
              width="6"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-42"
              fill="#DEDEE0"
              x="11"
              y="49"
              width="6"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-35"
              fill="#DEDEE0"
              x="35"
              y="28"
              width="6"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-43"
              fill="#5B7CE3"
              x="35"
              y="49"
              width="6"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-30"
              fill="#DEDEE0"
              x="23"
              y="28"
              width="6"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-44"
              fill="#DEDEE0"
              x="23"
              y="49"
              width="6"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-36"
              fill="#DEDEE0"
              x="47"
              y="28"
              width="6"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-45"
              fill="#DEDEE0"
              x="47"
              y="49"
              width="6"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-28"
              stroke="#DEDEE0"
              x="33.5"
              y="13.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-46"
              stroke="#DEDEE0"
              fill="#5B7CE3"
              x="33.5"
              y="34.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-31"
              stroke="#DEDEE0"
              fill="#EDEDEE"
              x="21.5"
              y="13.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-47"
              stroke="#DEDEE0"
              x="21.5"
              y="34.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-34"
              stroke="#DEDEE0"
              x="45.5"
              y="13.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-48"
              stroke="#DEDEE0"
              x="45.5"
              y="34.5"
              width="9"
              height="9"
              rx="2"
            />
          </g>
        </g>
      </g>
    </svg>
  );
};

export default DisplayPartial;
