import React from 'react';

const DisplayAll = () => {
  return (
    <svg
      width="64px"
      height="64px"
      viewBox="0 0 64 64"
      version="1.1"
      xmlns="http://www.w3.org/2000/svg"
      xmlnsXlink="http://www.w3.org/1999/xlink"
    >
      <title>Group 5</title>
      <g id="page" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
        <g
          id="6.3.1.7.a(D)_首頁_商品分類_分類彈窗"
          transform="translate(-1186.000000, -576.000000)"
        >
          <g id="Group-5" transform="translate(1186.000000, 576.000000)">
            <rect
              id="Rectangle-4-Copy-10"
              stroke="#D6DFF2"
              fill="#FFFFFF"
              x="0.5"
              y="0.5"
              width="63"
              height="63"
              rx="5"
            />
            <rect
              id="Rectangle-Copy-49"
              stroke="#DEDEE0"
              x="9.5"
              y="8.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-58"
              stroke="#DEDEE0"
              x="9.5"
              y="34.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-50"
              fill="#EDEDEE"
              x="9"
              y="27"
              width="10"
              height="3"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-60"
              fill="#EDEDEE"
              x="9"
              y="53"
              width="10"
              height="3"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-52"
              fill="#EDEDEE"
              x="21"
              y="27"
              width="10"
              height="3"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-53"
              fill="#EDEDEE"
              x="33"
              y="27"
              width="10"
              height="3"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-62"
              fill="#EDEDEE"
              x="21"
              y="53"
              width="10"
              height="3"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-64"
              fill="#5B7CE3"
              x="33"
              y="53"
              width="10"
              height="3"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-56"
              fill="#EDEDEE"
              x="45"
              y="27"
              width="10"
              height="3"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-66"
              fill="#EDEDEE"
              x="45"
              y="53"
              width="10"
              height="3"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-51"
              fill="#DEDEE0"
              x="9"
              y="20"
              width="10"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-68"
              fill="#DEDEE0"
              x="9"
              y="46"
              width="10"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-70"
              fill="#5B7CE3"
              x="33"
              y="46"
              width="10"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-55"
              fill="#DEDEE0"
              x="21"
              y="20"
              width="10"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-61"
              fill="#DEDEE0"
              x="33"
              y="20"
              width="10"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-72"
              fill="#DEDEE0"
              x="21"
              y="46"
              width="10"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-57"
              fill="#DEDEE0"
              x="45"
              y="20"
              width="10"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-73"
              fill="#DEDEE0"
              x="45"
              y="46"
              width="10"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-59"
              fill="#DEDEE0"
              x="11"
              y="23"
              width="6"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-74"
              fill="#DEDEE0"
              x="11"
              y="49"
              width="6"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-75"
              fill="#5B7CE3"
              x="35"
              y="49"
              width="6"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-63"
              fill="#DEDEE0"
              x="23"
              y="23"
              width="6"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-67"
              fill="#DEDEE0"
              x="35"
              y="23"
              width="6"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-76"
              fill="#DEDEE0"
              x="23"
              y="49"
              width="6"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-65"
              fill="#DEDEE0"
              x="47"
              y="23"
              width="6"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-77"
              fill="#DEDEE0"
              x="47"
              y="49"
              width="6"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-78"
              stroke="#DEDEE0"
              fill="#5B7CE3"
              x="33.5"
              y="34.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-69"
              stroke="#DEDEE0"
              fill="#EDEDEE"
              x="21.5"
              y="8.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-81"
              stroke="#DEDEE0"
              x="33.5"
              y="8.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-79"
              stroke="#DEDEE0"
              x="21.5"
              y="34.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-71"
              stroke="#DEDEE0"
              x="45.5"
              y="8.5"
              width="9"
              height="9"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-80"
              stroke="#DEDEE0"
              x="45.5"
              y="34.5"
              width="9"
              height="9"
              rx="2"
            />
          </g>
        </g>
      </g>
    </svg>
  );
};

export default DisplayAll;
