import React from 'react';

const FooterHorizontal = () => {
  return (
    <svg
      width="64px"
      height="64px"
      viewBox="0 0 64 64"
      version="1.1"
      xmlns="http://www.w3.org/2000/svg"
      xmlnsXlink="http://www.w3.org/1999/xlink"
    >
      <title>Group 4</title>
      <g id="page" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
        <g
          id="6.3.1.10.b(D)_首頁_頁腳_樣式選擇展開"
          transform="translate(-1230.000000, -309.000000)"
        >
          <g id="Group-4" transform="translate(1230.000000, 309.000000)">
            <rect
              id="Rectangle-4-Copy-8"
              stroke="#D6DFF2"
              fill="#FFFFFF"
              x="0.5"
              y="0.5"
              width="63"
              height="63"
              rx="5"
            />
            <rect
              id="Rectangle-Copy-13"
              stroke="#DEDEE0"
              x="8.5"
              y="34.5"
              width="47"
              height="21"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-49"
              fill="#DEDEE0"
              x="12"
              y="38"
              width="11"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-89"
              fill="#DEDEE0"
              x="27"
              y="38"
              width="11"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-98"
              fill="#DEDEE0"
              x="42"
              y="38"
              width="10"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-87"
              fill="#DEDEE0"
              x="12"
              y="46"
              width="11"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-90"
              fill="#DEDEE0"
              x="27"
              y="46"
              width="11"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-99"
              fill="#DEDEE0"
              x="42"
              y="46"
              width="10"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-86"
              fill="#DEDEE0"
              x="12"
              y="42"
              width="11"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-91"
              fill="#DEDEE0"
              x="27"
              y="42"
              width="11"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-100"
              fill="#DEDEE0"
              x="42"
              y="42"
              width="10"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-88"
              fill="#DEDEE0"
              x="12"
              y="50"
              width="7"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-92"
              fill="#DEDEE0"
              x="27"
              y="50"
              width="7"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-101"
              fill="#DEDEE0"
              x="42"
              y="50"
              width="6"
              height="2"
              rx="1"
            />
          </g>
        </g>
      </g>
    </svg>
  );
};

export default FooterHorizontal;
