import React from 'react';

const ThreeDimensionMenu = () => {
  return (
    <svg
      width="64px"
      height="64px"
      viewBox="0 0 64 64"
      version="1.1"
      xmlns="http://www.w3.org/2000/svg"
      xmlnsXlink="http://www.w3.org/1999/xlink"
    >
      <title>Group 5</title>
      <g id="page" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
        <g
          id="6.3.1.2.d(D)_首頁_導覽列_選單樣式選擇"
          transform="translate(-1230.000000, -343.000000)"
        >
          <g id="Group-5" transform="translate(1230.000000, 343.000000)">
            <rect
              id="Rectangle-4-Copy-15"
              stroke="#D6DFF2"
              fill="#FFFFFF"
              x="0.5"
              y="0.5"
              width="63"
              height="63"
              rx="5"
            />
            <rect
              id="Rectangle-Copy-117"
              stroke="#DEDEE0"
              x="18.5"
              y="26.5"
              width="15"
              height="19"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-124"
              stroke="#DEDEE0"
              x="35.5"
              y="37.5"
              width="15"
              height="20"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-118"
              stroke="#DEDEE0"
              x="28.5"
              y="8.5"
              width="7"
              height="7"
              rx="2"
            />
            <rect
              id="Rectangle-Copy-119"
              fill="#DEDEE0"
              x="8"
              y="20"
              width="9"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-130"
              fill="#DEDEE0"
              x="34"
              y="20"
              width="9"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-129"
              fill="#5B7CE3"
              x="21"
              y="20"
              width="9"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-131"
              fill="#DEDEE0"
              x="47"
              y="20"
              width="9"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-120"
              fill="#DEDEE0"
              x="22"
              y="30"
              width="8"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-125"
              fill="#5B7CE3"
              x="39"
              y="41"
              width="8"
              height="1"
              rx="0.5"
            />
            <rect
              id="Rectangle-Copy-127"
              fill="#DEDEE0"
              x="39"
              y="49"
              width="8"
              height="1"
              rx="0.5"
            />
            <rect
              id="Rectangle-Copy-126"
              fill="#DEDEE0"
              x="39"
              y="45"
              width="8"
              height="1"
              rx="0.5"
            />
            <rect
              id="Rectangle-Copy-128"
              fill="#DEDEE0"
              x="39"
              y="53"
              width="8"
              height="1"
              rx="0.5"
            />
            <rect
              id="Rectangle-Copy-122"
              fill="#5B7CE3"
              x="22"
              y="40"
              width="8"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-121"
              fill="#DEDEE0"
              x="22"
              y="35"
              width="8"
              height="2"
              rx="1"
            />
          </g>
        </g>
      </g>
    </svg>
  );
};

export default ThreeDimensionMenu;
