import React from 'react';

const TwoDimensionMenu = () => {
  return (
    <svg
      width="64px"
      height="64px"
      viewBox="0 0 64 64"
      version="1.1"
      xmlns="http://www.w3.org/2000/svg"
      xmlnsXlink="http://www.w3.org/1999/xlink"
    >
      <title>Group 6</title>
      <g id="page" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
        <g
          id="6.3.1.2.d(D)_首頁_導覽列_選單樣式選擇"
          transform="translate(-1230.000000, -419.000000)"
        >
          <g id="Group-6" transform="translate(1230.000000, 419.000000)">
            <g id="Group-4">
              <rect
                id="Rectangle-4-Copy-8"
                stroke="#D6DFF2"
                fill="#FFFFFF"
                x="0.5"
                y="0.5"
                width="63"
                height="63"
                rx="5"
              />
              <rect
                id="Rectangle-Copy-13"
                stroke="#DEDEE0"
                x="8.5"
                y="26.5"
                width="47"
                height="21"
                rx="2"
              />
              <rect
                id="Rectangle-Copy-18"
                stroke="#DEDEE0"
                x="28.5"
                y="8.5"
                width="7"
                height="7"
                rx="2"
              />
              <rect
                id="Rectangle-Copy-102"
                fill="#DEDEE0"
                x="16"
                y="30"
                width="8"
                height="2"
                rx="1"
              />
              <rect
                id="Rectangle-Copy-107"
                fill="#DEDEE0"
                x="28"
                y="30"
                width="8"
                height="2"
                rx="1"
              />
              <rect
                id="Rectangle-Copy-112"
                fill="#5B7CE3"
                x="40"
                y="30"
                width="8"
                height="2"
                rx="1"
              />
              <rect
                id="Rectangle-Copy-103"
                fill="#DEDEE0"
                x="16"
                y="34"
                width="8"
                height="1"
                rx="0.5"
              />
              <rect
                id="Rectangle-Copy-108"
                fill="#DEDEE0"
                x="28"
                y="34"
                width="8"
                height="1"
                rx="0.5"
              />
              <rect
                id="Rectangle-Copy-113"
                fill="#5B7CE3"
                x="40"
                y="34"
                width="8"
                height="1"
                rx="0.5"
              />
              <rect
                id="Rectangle-Copy-105"
                fill="#DEDEE0"
                x="16"
                y="40"
                width="8"
                height="1"
                rx="0.5"
              />
              <rect
                id="Rectangle-Copy-109"
                fill="#DEDEE0"
                x="28"
                y="40"
                width="8"
                height="1"
                rx="0.5"
              />
              <rect
                id="Rectangle-Copy-114"
                fill="#DEDEE0"
                x="40"
                y="40"
                width="8"
                height="1"
                rx="0.5"
              />
              <rect
                id="Rectangle-Copy-104"
                fill="#DEDEE0"
                x="16"
                y="37"
                width="8"
                height="1"
                rx="0.5"
              />
              <rect
                id="Rectangle-Copy-110"
                fill="#DEDEE0"
                x="28"
                y="37"
                width="8"
                height="1"
                rx="0.5"
              />
              <rect
                id="Rectangle-Copy-115"
                fill="#DEDEE0"
                x="40"
                y="37"
                width="8"
                height="1"
                rx="0.5"
              />
              <rect
                id="Rectangle-Copy-106"
                fill="#DEDEE0"
                x="16"
                y="43"
                width="8"
                height="1"
                rx="0.5"
              />
              <rect
                id="Rectangle-Copy-111"
                fill="#DEDEE0"
                x="28"
                y="43"
                width="8"
                height="1"
                rx="0.5"
              />
              <rect
                id="Rectangle-Copy-116"
                fill="#DEDEE0"
                x="40"
                y="43"
                width="8"
                height="1"
                rx="0.5"
              />
            </g>
            <rect
              id="Rectangle-Copy-119"
              fill="#DEDEE0"
              x="8"
              y="20"
              width="9"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-130"
              fill="#DEDEE0"
              x="34"
              y="20"
              width="9"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-129"
              fill="#5B7CE3"
              x="21"
              y="20"
              width="9"
              height="2"
              rx="1"
            />
            <rect
              id="Rectangle-Copy-131"
              fill="#DEDEE0"
              x="47"
              y="20"
              width="9"
              height="2"
              rx="1"
            />
          </g>
        </g>
      </g>
    </svg>
  );
};

export default TwoDimensionMenu;
